### PR TITLE
Fix importer prop sorting causes parents to be parsed after their chi…

### LINKED ISSUE #980: Importing template not working - order
`store.import` takes a JSON-AD string that can have multiple`local-id` items. The current import / parse implementation is _order dependent_, because sometimes a resource can refer to another resource that is not created yet:

- If a `property` is used before it's defined
- If a `parent` is used before it's defined

@Polleps implemented sorting in the parser to prioritize properties, which solves some cases, but there still are failure cases, e.g. when importing the new template (#959).

### PR DESCRIPTION
**Pull request by Polleps**
…ld properties #980

## Related Issues

closes #980

## Checklist
- [x] Add changelog entry linking to issue, describe API changes
- [x] Add or update tests if needed
- [ ] Update docs if needed

### CODE REVIEW

File: lib/src/parse.rs [hunk 1]
```diff
@@ -127,6 +178,8 @@ pub fn parse_json_ad_string(
                 b_is_prop.cmp(&a_is_prop)
             });
 
+            arr = pull_parents_of_props_to_front(&arr);
```
Comment (joepio) [inline lib/src/parse.rs:184]: This kinda stuff needs some documentation / comments / explanation IMO
